<?php

return [
    'Settings'                                                                                                                                                                                                      => 'Einstellungen',
    'Info'                                                                                                                                                                                                          => 'Info',
    'Notify On Comment Settings'                                                                                                                                                                                    => 'Notify On Comment Einstellungen',
    'Notify Users'                                                                                                                                                                                                  => 'Benachrichtige Benutzer',
    '- Select User -'                                                                                                                                                                                               => '- Wähle Nutzer -',
    'Loading users...'                                                                                                                                                                                              => 'Lade Benutzer...',
    'Add'                                                                                                                                                                                                           => 'Hinzufügen',
    'You can add your first user using the input field above. Go ahead!'                                                                                                                                            => 'Du kannst Deinen ersten Nutzer hinzufügen, indem Du das Feld oben nutzt. Lege einfach los! ',
    'Save'                                                                                                                                                                                                          => 'Speichern',
    'Notify On Comment Info'                                                                                                                                                                                        => 'Notify On Comment Info',
    'Getting help'                                                                                                                                                                                                  => 'Hilfe erhalten',
    'You have problems using this extension? Join the Pagekit community forum.'                                                                                                                                     => 'Probleme bei der Verwendung dieser Erweiterung? Im Pagekit-Forum findet sich bestimmt eine Lösung.',
    'Donate'                                                                                                                                                                                                        => 'Spenden',
    'Do you like my extensions? They are free. Of course I would like to get a donation, so if you want to, please open the donate link. You may find three possibilities to donate: PayPal, Patreon and Coinhive.' => 'Ist diese Erweiterung hilfreich? Sie ist kostenfrei! Natürlich freue ich mich aber über eine kleine Spende. Der Spenden-Link öffnet eine neue Seite, die drei mögliche Spendenmöglichkeiten zeigt: PayPal, Patreon und Coinhive.',
    'A new comment has been created on %sitename%.'                                                                                                                                                                 => 'Auf %sitename% wurde ein neuer Kommentar verfasst.',
    'Moderate comments'                                                                                                                                                                                             => 'Kommentare moderieren',
    'Author:'                                                                                                                                                                                                       => 'Autor:',
    'IP:'                                                                                                                                                                                                           => 'IP:',
    'Unable to send mail.'                                                                                                                                                                                          => 'E-Mail konnte nicht gesendet werden.',
];